/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    agents: Agent;
    'commission-tiers': CommissionTier;
    'notifications-log': NotificationsLog;
    banners: Banner;
    promos: Promo;
    testimonials: Testimonial;
    faqs: Faq;
    'blog-posts': BlogPost;
    providers: Provider;
    'patch-providers': PatchProvider;
    games: Game;
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    agents: AgentsSelect<false> | AgentsSelect<true>;
    'commission-tiers': CommissionTiersSelect<false> | CommissionTiersSelect<true>;
    'notifications-log': NotificationsLogSelect<false> | NotificationsLogSelect<true>;
    banners: BannersSelect<false> | BannersSelect<true>;
    promos: PromosSelect<false> | PromosSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    providers: ProvidersSelect<false> | ProvidersSelect<true>;
    'patch-providers': PatchProvidersSelect<false> | PatchProvidersSelect<true>;
    games: GamesSelect<false> | GamesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'popup-announcement': PopupAnnouncement;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'popup-announcement': PopupAnnouncementSelect<false> | PopupAnnouncementSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Senarai agent yang mendaftar melalui website. Gunakan filter untuk cari agent mengikut status.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents".
 */
export interface Agent {
  id: number;
  name: string;
  experience?: ('baru' | 'berpengalaman') | null;
  phone: string;
  /**
   * Kosongkan jika sama dengan nombor telefon.
   */
  whatsapp?: string | null;
  /**
   * Mesej yang ditulis oleh agent semasa pendaftaran.
   */
  message?: string | null;
  /**
   * Tambah nota setiap kali follow-up atau ada perkembangan baru.
   */
  notes?:
    | {
        note: string;
        addedBy?: string | null;
        addedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Tukar status selepas follow-up.
   */
  status?: ('pending' | 'contacted' | 'approved' | 'rejected') | null;
  /**
   * Auto-generated. Klik untuk chat terus dengan agent.
   */
  whatsappLink?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Struktur komisyen mengikut tier agent. Dipaparkan di homepage sebagai kad tier.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commission-tiers".
 */
export interface CommissionTier {
  id: number;
  /**
   * Contoh: Agent Biasa, Senior Agent, Master Agent
   */
  name: string;
  /**
   * Peratusan komisyen. Contoh: 25, 35, 45
   */
  percentage: number;
  /**
   * Jumlah minimum downline untuk layak tier ini.
   */
  minDownline?: number | null;
  /**
   * Warna hex untuk badge tier di frontend. Contoh: #d4a853
   */
  color?: string | null;
  /**
   * Senarai kelebihan yang dipapar di kad tier.
   */
  benefits?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  icon?: ('star' | 'crown' | 'diamond' | 'rocket') | null;
  /**
   * Nombor kecil = papar dulu.
   */
  order?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Log semua notifikasi yang dihantar (Telegram, WhatsApp, Email). Filter mengikut saluran atau status.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications-log".
 */
export interface NotificationsLog {
  id: number;
  title: string;
  /**
   * Kandungan yang dihantar.
   */
  message: string;
  /**
   * Chat ID, nombor telefon, atau email penerima.
   */
  recipient?: string | null;
  channel: 'telegram' | 'whatsapp' | 'email';
  status?: ('sent' | 'failed' | 'pending') | null;
  relatedAgent?: (number | null) | Agent;
  /**
   * Mesej ralat jika notifikasi gagal dihantar.
   */
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Banner carousel di bahagian atas homepage. Susun mengikut "Susunan".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners".
 */
export interface Banner {
  id: number;
  /**
   * Nama dalaman untuk mengenal pasti banner. Tidak dipapar di frontend.
   */
  title: string;
  /**
   * Upload gambar banner. Saiz disyorkan: 1920 x 640 piksel.
   */
  image?: (number | null) | Media;
  /**
   * Guna URL jika tiada upload. Salah satu sahaja diperlukan.
   */
  imageUrl?: string | null;
  /**
   * URL apabila banner diklik. Kosongkan jika tiada.
   */
  link?: string | null;
  /**
   * Nombor kecil = papar dulu.
   */
  order?: number | null;
  /**
   * Nyahaktif untuk sembunyikan tanpa delete.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Semua gambar dan fail media untuk website. Gunakan kategori untuk susun.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Penerangan gambar untuk SEO dan accessibility.
   */
  alt: string;
  category?: ('banner' | 'avatar' | 'blog' | 'provider' | 'game' | 'other') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    banner?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Kad promosi yang dipaparkan di homepage. Toggle "Highlight" untuk featured.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promos".
 */
export interface Promo {
  id: number;
  title: string;
  /**
   * Poin-poin yang dipapar dalam kad promosi.
   */
  items?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  ctaText?: string | null;
  /**
   * URL yang dibuka apabila butang diklik.
   */
  ctaLink?: string | null;
  icon?: ('bonus' | 'star' | 'vip') | null;
  /**
   * Aktifkan untuk jadikan kad ini lebih menonjol.
   */
  highlight?: boolean | null;
  /**
   * Nombor kecil = papar dulu.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Testimoni agent & paparan pendapatan untuk homepage. Filter mengikut jenis.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  role?: string | null;
  /**
   * Testimoni yang diberikan oleh agent. Dipaparkan di homepage.
   */
  content?: string | null;
  avatar?: (number | null) | Media;
  /**
   * Guna URL luaran jika tiada upload. Salah satu sahaja diperlukan.
   */
  avatarUrl?: string | null;
  /**
   * Rating 1-5 bintang. Default: 5.
   */
  rating?: number | null;
  /**
   * Jumlah pendapatan yang dipaparkan.
   */
  income?: string | null;
  period?: string | null;
  /**
   * Peratusan pertumbuhan pendapatan.
   */
  growth?: string | null;
  /**
   * Lebar bar pendapatan (0-100%). Dipapar sebagai visual bar di frontend.
   */
  bar?: number | null;
  /**
   * Tentukan jenis entry ini.
   */
  type?: ('income' | 'testimonial') | null;
  featured?: boolean | null;
  /**
   * Nombor kecil = papar dulu.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Soalan lazim (FAQ) untuk website. Filter mengikut kategori.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  category?: ('general' | 'agent' | 'commission' | 'technical') | null;
  /**
   * Nombor kecil = papar dulu.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Artikel blog untuk SEO dan content marketing. Filter mengikut kategori atau status.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * Auto-generated dari tajuk. Ini jadi URL artikel, cth: /blog/cara-jadi-agent-cm8
   */
  slug: string;
  /**
   * Ringkasan pendek (1-2 ayat). Dipapar di senarai blog dan sebagai SEO meta description.
   */
  excerpt?: string | null;
  /**
   * Gambar yang dipapar sebagai thumbnail dan header artikel.
   */
  featuredImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  seo?: {
    /**
     * Tajuk yang dipapar di Google. Max 60 aksara.
     */
    metaTitle?: string | null;
    /**
     * Penerangan di Google search. Max 160 aksara.
     */
    metaDescription?: string | null;
  };
  category?: ('tips' | 'guide' | 'news' | 'promo') | null;
  /**
   * Tukar ke "Diterbitkan" untuk live.
   */
  status?: ('draft' | 'published') | null;
  /**
   * Auto-set apabila diterbitkan.
   */
  publishedDate?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Provider permainan yang dipaparkan di homepage. Toggle "Papar di Homepage" untuk kawal visibility.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providers".
 */
export interface Provider {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  /**
   * Guna URL luaran jika tiada upload.
   */
  logoUrl?: string | null;
  /**
   * Nombor kecil = papar dulu.
   */
  order?: number | null;
  showOnHomepage?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Provider untuk Patch ID Scanner (Pragmatic, JILI, dll). Setiap provider ada ID unik.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patch-providers".
 */
export interface PatchProvider {
  id: number;
  name: string;
  /**
   * ID unik yang digunakan oleh system. Huruf kecil sahaja.
   */
  providerId: string;
  logo?: (number | null) | Media;
  /**
   * Guna URL luaran jika tiada upload.
   */
  logoUrl?: string | null;
  /**
   * Nombor kecil = papar dulu.
   */
  order?: number | null;
  /**
   * Nyahaktif untuk sembunyikan tanpa delete.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Senarai permainan slot untuk Patch ID Scanner. Setiap game mesti ada Provider ID.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "games".
 */
export interface Game {
  id: number;
  name: string;
  /**
   * Mesti sama dengan Provider ID dalam Patch Providers.
   */
  provider: string;
  image?: (number | null) | Media;
  /**
   * Guna URL luaran jika tiada upload. Salah satu sahaja diperlukan.
   */
  imageUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pengguna admin yang boleh mengakses panel ini. Setiap pengguna ada peranan tersendiri.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Gambar profil pengguna.
   */
  avatar?: (number | null) | Media;
  /**
   * Super Admin: full access. Editor: edit content. Viewer: read only.
   */
  role?: ('super-admin' | 'editor' | 'viewer') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'agents';
        value: number | Agent;
      } | null)
    | ({
        relationTo: 'commission-tiers';
        value: number | CommissionTier;
      } | null)
    | ({
        relationTo: 'notifications-log';
        value: number | NotificationsLog;
      } | null)
    | ({
        relationTo: 'banners';
        value: number | Banner;
      } | null)
    | ({
        relationTo: 'promos';
        value: number | Promo;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'providers';
        value: number | Provider;
      } | null)
    | ({
        relationTo: 'patch-providers';
        value: number | PatchProvider;
      } | null)
    | ({
        relationTo: 'games';
        value: number | Game;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents_select".
 */
export interface AgentsSelect<T extends boolean = true> {
  name?: T;
  experience?: T;
  phone?: T;
  whatsapp?: T;
  message?: T;
  notes?:
    | T
    | {
        note?: T;
        addedBy?: T;
        addedAt?: T;
        id?: T;
      };
  status?: T;
  whatsappLink?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commission-tiers_select".
 */
export interface CommissionTiersSelect<T extends boolean = true> {
  name?: T;
  percentage?: T;
  minDownline?: T;
  color?: T;
  benefits?:
    | T
    | {
        text?: T;
        id?: T;
      };
  icon?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications-log_select".
 */
export interface NotificationsLogSelect<T extends boolean = true> {
  title?: T;
  message?: T;
  recipient?: T;
  channel?: T;
  status?: T;
  relatedAgent?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners_select".
 */
export interface BannersSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  imageUrl?: T;
  link?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promos_select".
 */
export interface PromosSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        text?: T;
        id?: T;
      };
  ctaText?: T;
  ctaLink?: T;
  icon?: T;
  highlight?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  content?: T;
  avatar?: T;
  avatarUrl?: T;
  rating?: T;
  income?: T;
  period?: T;
  growth?: T;
  bar?: T;
  type?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  category?: T;
  status?: T;
  publishedDate?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providers_select".
 */
export interface ProvidersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  logoUrl?: T;
  order?: T;
  showOnHomepage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patch-providers_select".
 */
export interface PatchProvidersSelect<T extends boolean = true> {
  name?: T;
  providerId?: T;
  logo?: T;
  logoUrl?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "games_select".
 */
export interface GamesSelect<T extends boolean = true> {
  name?: T;
  provider?: T;
  image?: T;
  imageUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        banner?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Tetapan umum untuk website CM8 VVIP.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  tagline?: string | null;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  heroCTA?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * Teks butang utama (oren/gradient)
   */
  ctaButton1Text?: string | null;
  /**
   * URL yang dituju bila klik butang utama
   */
  ctaButton1Link?: string | null;
  /**
   * Teks butang kedua (outline)
   */
  ctaButton2Text?: string | null;
  /**
   * URL yang dituju bila klik butang kedua
   */
  ctaButton2Link?: string | null;
  /**
   * Format: 60123456789 (tanpa + atau -)
   */
  whatsappNumber?: string | null;
  telegramLink?: string | null;
  /**
   * Link group Telegram komuniti agent. Dipapar di halaman Info & Blog.
   */
  telegramGroupLink?: string | null;
  /**
   * Link group WhatsApp komuniti agent.
   */
  whatsappGroupLink?: string | null;
  /**
   * Link WhatsApp untuk chat terus dengan admin / pendaftaran agent baru.
   */
  adminWhatsappLink?: string | null;
  footerText?: string | null;
  socialLinks?:
    | {
        platform?: ('facebook' | 'instagram' | 'twitter' | 'youtube' | 'tiktok') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  /**
   * Pisahkan dengan koma. Contoh: agent cm8, buat duit online
   */
  keywords?: string | null;
  ogImage?: (number | null) | Media;
  tickerEnabled?: boolean | null;
  tickerMessages?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Percentage terendah yang boleh keluar (default: 30%)
   */
  scannerMinRtp?: number | null;
  /**
   * Percentage tertinggi yang boleh keluar (default: 97%)
   */
  scannerMaxRtp?: number | null;
  /**
   * RTP ≥ nilai ini = 🔥 HOT
   */
  scannerHotThreshold?: number | null;
  /**
   * RTP ≥ nilai ini = ⚡ WARM, bawah = ❄️ COLD
   */
  scannerWarmThreshold?: number | null;
  /**
   * Berapa % game yang akan jadi HOT (default: 10%)
   */
  scannerHotPercent?: number | null;
  /**
   * Berapa % game yang akan jadi WARM (default: 30%)
   */
  scannerWarmPercent?: number | null;
  /**
   * Auto-kira: selebihnya jadi ❄️ COLD
   */
  scannerColdPercent?: number | null;
  /**
   * Result scan akan berubah setiap interval ini. Semua user nampak result sama dalam tempoh yang sama.
   */
  scannerSeedInterval?: ('15' | '30' | '60' | '180') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Popup modal yang dipaparkan di homepage. Boleh toggle on/off.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "popup-announcement".
 */
export interface PopupAnnouncement {
  id: number;
  enabled?: boolean | null;
  title?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  ctaText?: string | null;
  /**
   * Jika ada, butang akan redirect ke link ini.
   */
  ctaLink?: string | null;
  /**
   * Jika aktif, popup hanya dipapar sekali per sesi.
   */
  showOnce?: boolean | null;
  backgroundColor?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  favicon?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  heroCTA?: T;
  heroImage?: T;
  ctaButton1Text?: T;
  ctaButton1Link?: T;
  ctaButton2Text?: T;
  ctaButton2Link?: T;
  whatsappNumber?: T;
  telegramLink?: T;
  telegramGroupLink?: T;
  whatsappGroupLink?: T;
  adminWhatsappLink?: T;
  footerText?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  keywords?: T;
  ogImage?: T;
  tickerEnabled?: T;
  tickerMessages?:
    | T
    | {
        text?: T;
        id?: T;
      };
  scannerMinRtp?: T;
  scannerMaxRtp?: T;
  scannerHotThreshold?: T;
  scannerWarmThreshold?: T;
  scannerHotPercent?: T;
  scannerWarmPercent?: T;
  scannerColdPercent?: T;
  scannerSeedInterval?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "popup-announcement_select".
 */
export interface PopupAnnouncementSelect<T extends boolean = true> {
  enabled?: T;
  title?: T;
  content?: T;
  image?: T;
  ctaText?: T;
  ctaLink?: T;
  showOnce?: T;
  backgroundColor?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}