/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  boolean,
  jsonb,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_agents_experience = pgEnum('enum_agents_experience', ['baru', 'berpengalaman'])
export const enum_agents_status = pgEnum('enum_agents_status', [
  'pending',
  'contacted',
  'approved',
  'rejected',
])
export const enum_commission_tiers_icon = pgEnum('enum_commission_tiers_icon', [
  'star',
  'crown',
  'diamond',
  'rocket',
])
export const enum_notifications_log_channel = pgEnum('enum_notifications_log_channel', [
  'telegram',
  'whatsapp',
  'email',
])
export const enum_notifications_log_status = pgEnum('enum_notifications_log_status', [
  'sent',
  'failed',
  'pending',
])
export const enum_promos_icon = pgEnum('enum_promos_icon', ['bonus', 'star', 'vip'])
export const enum_testimonials_type = pgEnum('enum_testimonials_type', ['income', 'testimonial'])
export const enum_faqs_category = pgEnum('enum_faqs_category', [
  'general',
  'agent',
  'commission',
  'technical',
])
export const enum_blog_posts_category = pgEnum('enum_blog_posts_category', [
  'tips',
  'guide',
  'news',
  'promo',
])
export const enum_blog_posts_status = pgEnum('enum_blog_posts_status', ['draft', 'published'])
export const enum__blog_posts_v_version_category = pgEnum('enum__blog_posts_v_version_category', [
  'tips',
  'guide',
  'news',
  'promo',
])
export const enum__blog_posts_v_version_status = pgEnum('enum__blog_posts_v_version_status', [
  'draft',
  'published',
])
export const enum_users_role = pgEnum('enum_users_role', ['super-admin', 'editor', 'viewer'])
export const enum_media_category = pgEnum('enum_media_category', [
  'banner',
  'avatar',
  'blog',
  'provider',
  'game',
  'other',
])
export const enum_site_settings_social_links_platform = pgEnum(
  'enum_site_settings_social_links_platform',
  ['facebook', 'instagram', 'twitter', 'youtube', 'tiktok'],
)
export const enum_site_settings_scanner_seed_interval = pgEnum(
  'enum_site_settings_scanner_seed_interval',
  ['15', '30', '60', '180'],
)

export const agents_notes = pgTable(
  'agents_notes',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    note: varchar('note').notNull(),
    addedBy: varchar('added_by'),
    addedAt: timestamp('added_at', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('agents_notes_order_idx').on(columns._order),
    index('agents_notes_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [agents.id],
      name: 'agents_notes_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const agents = pgTable(
  'agents',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    experience: enum_agents_experience('experience').default('baru'),
    phone: varchar('phone').notNull(),
    whatsapp: varchar('whatsapp'),
    message: varchar('message'),
    status: enum_agents_status('status').default('pending'),
    whatsappLink: varchar('whatsapp_link'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('agents_updated_at_idx').on(columns.updatedAt),
    index('agents_created_at_idx').on(columns.createdAt),
  ],
)

export const commission_tiers_benefits = pgTable(
  'commission_tiers_benefits',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    text: varchar('text').notNull(),
  },
  (columns) => [
    index('commission_tiers_benefits_order_idx').on(columns._order),
    index('commission_tiers_benefits_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [commission_tiers.id],
      name: 'commission_tiers_benefits_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const commission_tiers = pgTable(
  'commission_tiers',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    percentage: numeric('percentage', { mode: 'number' }).notNull(),
    minDownline: numeric('min_downline', { mode: 'number' }).default(0),
    color: varchar('color').default('#d4a853'),
    icon: enum_commission_tiers_icon('icon').default('star'),
    order: numeric('order', { mode: 'number' }).default(0),
    active: boolean('active').default(true),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('commission_tiers_updated_at_idx').on(columns.updatedAt),
    index('commission_tiers_created_at_idx').on(columns.createdAt),
  ],
)

export const notifications_log = pgTable(
  'notifications_log',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    message: varchar('message').notNull(),
    recipient: varchar('recipient'),
    channel: enum_notifications_log_channel('channel').notNull(),
    status: enum_notifications_log_status('status').default('pending'),
    relatedAgent: integer('related_agent_id').references(() => agents.id, {
      onDelete: 'set null',
    }),
    errorMessage: varchar('error_message'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('notifications_log_related_agent_idx').on(columns.relatedAgent),
    index('notifications_log_updated_at_idx').on(columns.updatedAt),
    index('notifications_log_created_at_idx').on(columns.createdAt),
  ],
)

export const banners = pgTable(
  'banners',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    imageUrl: varchar('image_url'),
    link: varchar('link'),
    order: numeric('order', { mode: 'number' }).default(0),
    active: boolean('active').default(true),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('banners_image_idx').on(columns.image),
    index('banners_updated_at_idx').on(columns.updatedAt),
    index('banners_created_at_idx').on(columns.createdAt),
  ],
)

export const promos_items = pgTable(
  'promos_items',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    text: varchar('text').notNull(),
  },
  (columns) => [
    index('promos_items_order_idx').on(columns._order),
    index('promos_items_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [promos.id],
      name: 'promos_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const promos = pgTable(
  'promos',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    ctaText: varchar('cta_text').default('Claim Now'),
    ctaLink: varchar('cta_link'),
    icon: enum_promos_icon('icon').default('bonus'),
    highlight: boolean('highlight').default(false),
    order: numeric('order', { mode: 'number' }).default(0),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('promos_updated_at_idx').on(columns.updatedAt),
    index('promos_created_at_idx').on(columns.createdAt),
  ],
)

export const testimonials = pgTable(
  'testimonials',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    role: varchar('role').default('Agent Aktif'),
    content: varchar('content'),
    avatar: integer('avatar_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    avatarUrl: varchar('avatar_url'),
    rating: numeric('rating', { mode: 'number' }).default(5),
    income: varchar('income'),
    period: varchar('period').default('/minggu'),
    growth: varchar('growth'),
    bar: numeric('bar', { mode: 'number' }),
    type: enum_testimonials_type('type').default('income'),
    featured: boolean('featured').default(true),
    order: numeric('order', { mode: 'number' }).default(0),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('testimonials_avatar_idx').on(columns.avatar),
    index('testimonials_updated_at_idx').on(columns.updatedAt),
    index('testimonials_created_at_idx').on(columns.createdAt),
  ],
)

export const faqs = pgTable(
  'faqs',
  {
    id: serial('id').primaryKey(),
    question: varchar('question').notNull(),
    answer: varchar('answer').notNull(),
    category: enum_faqs_category('category').default('general'),
    order: numeric('order', { mode: 'number' }).default(0),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('faqs_updated_at_idx').on(columns.updatedAt),
    index('faqs_created_at_idx').on(columns.createdAt),
  ],
)

export const blog_posts = pgTable(
  'blog_posts',
  {
    id: serial('id').primaryKey(),
    title: varchar('title'),
    slug: varchar('slug'),
    excerpt: varchar('excerpt'),
    featuredImage: integer('featured_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    content: jsonb('content'),
    seo_metaTitle: varchar('seo_meta_title'),
    seo_metaDescription: varchar('seo_meta_description'),
    category: enum_blog_posts_category('category').default('tips'),
    status: enum_blog_posts_status('status').default('draft'),
    publishedDate: timestamp('published_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_blog_posts_status('_status').default('draft'),
  },
  (columns) => [
    uniqueIndex('blog_posts_slug_idx').on(columns.slug),
    index('blog_posts_featured_image_idx').on(columns.featuredImage),
    index('blog_posts_updated_at_idx').on(columns.updatedAt),
    index('blog_posts_created_at_idx').on(columns.createdAt),
    index('blog_posts__status_idx').on(columns._status),
  ],
)

export const _blog_posts_v = pgTable(
  '_blog_posts_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => blog_posts.id, {
      onDelete: 'set null',
    }),
    version_title: varchar('version_title'),
    version_slug: varchar('version_slug'),
    version_excerpt: varchar('version_excerpt'),
    version_featuredImage: integer('version_featured_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    version_content: jsonb('version_content'),
    version_seo_metaTitle: varchar('version_seo_meta_title'),
    version_seo_metaDescription: varchar('version_seo_meta_description'),
    version_category: enum__blog_posts_v_version_category('version_category').default('tips'),
    version_status: enum__blog_posts_v_version_status('version_status').default('draft'),
    version_publishedDate: timestamp('version_published_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__blog_posts_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
  },
  (columns) => [
    index('_blog_posts_v_parent_idx').on(columns.parent),
    index('_blog_posts_v_version_version_slug_idx').on(columns.version_slug),
    index('_blog_posts_v_version_version_featured_image_idx').on(columns.version_featuredImage),
    index('_blog_posts_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_blog_posts_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_blog_posts_v_version_version__status_idx').on(columns.version__status),
    index('_blog_posts_v_created_at_idx').on(columns.createdAt),
    index('_blog_posts_v_updated_at_idx').on(columns.updatedAt),
    index('_blog_posts_v_latest_idx').on(columns.latest),
  ],
)

export const providers = pgTable(
  'providers',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    logo: integer('logo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    logoUrl: varchar('logo_url'),
    order: numeric('order', { mode: 'number' }).default(0),
    showOnHomepage: boolean('show_on_homepage').default(true),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('providers_logo_idx').on(columns.logo),
    index('providers_updated_at_idx').on(columns.updatedAt),
    index('providers_created_at_idx').on(columns.createdAt),
  ],
)

export const patch_providers = pgTable(
  'patch_providers',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    providerId: varchar('provider_id').notNull(),
    logo: integer('logo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    logoUrl: varchar('logo_url'),
    order: numeric('order', { mode: 'number' }).default(0),
    active: boolean('active').default(true),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('patch_providers_provider_id_idx').on(columns.providerId),
    index('patch_providers_logo_idx').on(columns.logo),
    index('patch_providers_updated_at_idx').on(columns.updatedAt),
    index('patch_providers_created_at_idx').on(columns.createdAt),
  ],
)

export const games = pgTable(
  'games',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    provider: varchar('provider').notNull(),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    imageUrl: varchar('image_url'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('games_image_idx').on(columns.image),
    index('games_updated_at_idx').on(columns.updatedAt),
    index('games_created_at_idx').on(columns.createdAt),
  ],
)

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    avatar: integer('avatar_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    role: enum_users_role('role').default('editor'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_avatar_idx').on(columns.avatar),
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    category: enum_media_category('category').default('other'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
    sizes_thumbnail_url: varchar('sizes_thumbnail_url'),
    sizes_thumbnail_width: numeric('sizes_thumbnail_width', { mode: 'number' }),
    sizes_thumbnail_height: numeric('sizes_thumbnail_height', { mode: 'number' }),
    sizes_thumbnail_mimeType: varchar('sizes_thumbnail_mime_type'),
    sizes_thumbnail_filesize: numeric('sizes_thumbnail_filesize', { mode: 'number' }),
    sizes_thumbnail_filename: varchar('sizes_thumbnail_filename'),
    sizes_card_url: varchar('sizes_card_url'),
    sizes_card_width: numeric('sizes_card_width', { mode: 'number' }),
    sizes_card_height: numeric('sizes_card_height', { mode: 'number' }),
    sizes_card_mimeType: varchar('sizes_card_mime_type'),
    sizes_card_filesize: numeric('sizes_card_filesize', { mode: 'number' }),
    sizes_card_filename: varchar('sizes_card_filename'),
    sizes_banner_url: varchar('sizes_banner_url'),
    sizes_banner_width: numeric('sizes_banner_width', { mode: 'number' }),
    sizes_banner_height: numeric('sizes_banner_height', { mode: 'number' }),
    sizes_banner_mimeType: varchar('sizes_banner_mime_type'),
    sizes_banner_filesize: numeric('sizes_banner_filesize', { mode: 'number' }),
    sizes_banner_filename: varchar('sizes_banner_filename'),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
    index('media_sizes_thumbnail_sizes_thumbnail_filename_idx').on(
      columns.sizes_thumbnail_filename,
    ),
    index('media_sizes_card_sizes_card_filename_idx').on(columns.sizes_card_filename),
    index('media_sizes_banner_sizes_banner_filename_idx').on(columns.sizes_banner_filename),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    agentsID: integer('agents_id'),
    'commission-tiersID': integer('commission_tiers_id'),
    'notifications-logID': integer('notifications_log_id'),
    bannersID: integer('banners_id'),
    promosID: integer('promos_id'),
    testimonialsID: integer('testimonials_id'),
    faqsID: integer('faqs_id'),
    'blog-postsID': integer('blog_posts_id'),
    providersID: integer('providers_id'),
    'patch-providersID': integer('patch_providers_id'),
    gamesID: integer('games_id'),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_agents_id_idx').on(columns.agentsID),
    index('payload_locked_documents_rels_commission_tiers_id_idx').on(
      columns['commission-tiersID'],
    ),
    index('payload_locked_documents_rels_notifications_log_id_idx').on(
      columns['notifications-logID'],
    ),
    index('payload_locked_documents_rels_banners_id_idx').on(columns.bannersID),
    index('payload_locked_documents_rels_promos_id_idx').on(columns.promosID),
    index('payload_locked_documents_rels_testimonials_id_idx').on(columns.testimonialsID),
    index('payload_locked_documents_rels_faqs_id_idx').on(columns.faqsID),
    index('payload_locked_documents_rels_blog_posts_id_idx').on(columns['blog-postsID']),
    index('payload_locked_documents_rels_providers_id_idx').on(columns.providersID),
    index('payload_locked_documents_rels_patch_providers_id_idx').on(columns['patch-providersID']),
    index('payload_locked_documents_rels_games_id_idx').on(columns.gamesID),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['agentsID']],
      foreignColumns: [agents.id],
      name: 'payload_locked_documents_rels_agents_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['commission-tiersID']],
      foreignColumns: [commission_tiers.id],
      name: 'payload_locked_documents_rels_commission_tiers_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['notifications-logID']],
      foreignColumns: [notifications_log.id],
      name: 'payload_locked_documents_rels_notifications_log_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['bannersID']],
      foreignColumns: [banners.id],
      name: 'payload_locked_documents_rels_banners_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['promosID']],
      foreignColumns: [promos.id],
      name: 'payload_locked_documents_rels_promos_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['testimonialsID']],
      foreignColumns: [testimonials.id],
      name: 'payload_locked_documents_rels_testimonials_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['faqsID']],
      foreignColumns: [faqs.id],
      name: 'payload_locked_documents_rels_faqs_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['blog-postsID']],
      foreignColumns: [blog_posts.id],
      name: 'payload_locked_documents_rels_blog_posts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['providersID']],
      foreignColumns: [providers.id],
      name: 'payload_locked_documents_rels_providers_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['patch-providersID']],
      foreignColumns: [patch_providers.id],
      name: 'payload_locked_documents_rels_patch_providers_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['gamesID']],
      foreignColumns: [games.id],
      name: 'payload_locked_documents_rels_games_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const site_settings_social_links = pgTable(
  'site_settings_social_links',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    platform: enum_site_settings_social_links_platform('platform'),
    url: varchar('url'),
  },
  (columns) => [
    index('site_settings_social_links_order_idx').on(columns._order),
    index('site_settings_social_links_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [site_settings.id],
      name: 'site_settings_social_links_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const site_settings_ticker_messages = pgTable(
  'site_settings_ticker_messages',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    text: varchar('text').notNull(),
  },
  (columns) => [
    index('site_settings_ticker_messages_order_idx').on(columns._order),
    index('site_settings_ticker_messages_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [site_settings.id],
      name: 'site_settings_ticker_messages_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const site_settings = pgTable(
  'site_settings',
  {
    id: serial('id').primaryKey(),
    siteName: varchar('site_name').default('CM8 VVIP'),
    tagline: varchar('tagline').default('Platform Agent #1 Malaysia'),
    logo: integer('logo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    favicon: integer('favicon_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    heroTitle: varchar('hero_title').default('Jadi Agent CM8 Sekarang'),
    heroSubtitle: varchar('hero_subtitle').default(
      'Jana pendapatan lumayan dengan menjadi agent platform CM8. Komisyen tinggi, sokongan penuh, dan peluang tanpa had.',
    ),
    heroCTA: varchar('hero_c_t_a').default('Daftar Sekarang'),
    heroImage: integer('hero_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    ctaButton1Text: varchar('cta_button1_text').default('🚀 Jadi Agent Sekarang'),
    ctaButton1Link: varchar('cta_button1_link').default('https://masuk10.com/Wasapvvipcs'),
    ctaButton2Text: varchar('cta_button2_text').default('Daftar Akaun CM8'),
    ctaButton2Link: varchar('cta_button2_link').default('https://masuk10.com/Wasapvvipcs'),
    whatsappNumber: varchar('whatsapp_number'),
    telegramLink: varchar('telegram_link'),
    telegramGroupLink: varchar('telegram_group_link').default('https://t.me/+7qOP1Y8RQcthYjll'),
    whatsappGroupLink: varchar('whatsapp_group_link').default('https://masuk10.com/WasapGrupVVIP'),
    adminWhatsappLink: varchar('admin_whatsapp_link').default('https://masuk10.com/Wasapvvipcs'),
    footerText: varchar('footer_text').default('© 2026 CM8 VVIP. Semua hak cipta terpelihara.'),
    metaTitle: varchar('meta_title').default(
      'CM8 VVIP — Buat Duit Online & Agent Slot Tanpa Modal #1 Malaysia',
    ),
    metaDescription: varchar('meta_description').default(
      'Jana income pasif sebagai Agent Slot CM8 VVIP. Daftar percuma, tiada modal.',
    ),
    keywords: varchar('keywords'),
    ogImage: integer('og_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    tickerEnabled: boolean('ticker_enabled').default(true),
    scannerMinRtp: numeric('scanner_min_rtp', { mode: 'number' }).default(30),
    scannerMaxRtp: numeric('scanner_max_rtp', { mode: 'number' }).default(97),
    scannerHotThreshold: numeric('scanner_hot_threshold', { mode: 'number' }).default(85),
    scannerWarmThreshold: numeric('scanner_warm_threshold', { mode: 'number' }).default(65),
    scannerHotPercent: numeric('scanner_hot_percent', { mode: 'number' }).default(10),
    scannerWarmPercent: numeric('scanner_warm_percent', { mode: 'number' }).default(30),
    scannerColdPercent: numeric('scanner_cold_percent', { mode: 'number' }).default(60),
    scannerSeedInterval:
      enum_site_settings_scanner_seed_interval('scanner_seed_interval').default('60'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('site_settings_logo_idx').on(columns.logo),
    index('site_settings_favicon_idx').on(columns.favicon),
    index('site_settings_hero_image_idx').on(columns.heroImage),
    index('site_settings_og_image_idx').on(columns.ogImage),
  ],
)

export const popup_announcement = pgTable(
  'popup_announcement',
  {
    id: serial('id').primaryKey(),
    enabled: boolean('enabled').default(false),
    title: varchar('title'),
    content: jsonb('content'),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    ctaText: varchar('cta_text').default('Okay'),
    ctaLink: varchar('cta_link'),
    showOnce: boolean('show_once').default(true),
    backgroundColor: varchar('background_color').default('#1a1a2e'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [index('popup_announcement_image_idx').on(columns.image)],
)

export const relations_agents_notes = relations(agents_notes, ({ one }) => ({
  _parentID: one(agents, {
    fields: [agents_notes._parentID],
    references: [agents.id],
    relationName: 'notes',
  }),
}))
export const relations_agents = relations(agents, ({ many }) => ({
  notes: many(agents_notes, {
    relationName: 'notes',
  }),
}))
export const relations_commission_tiers_benefits = relations(
  commission_tiers_benefits,
  ({ one }) => ({
    _parentID: one(commission_tiers, {
      fields: [commission_tiers_benefits._parentID],
      references: [commission_tiers.id],
      relationName: 'benefits',
    }),
  }),
)
export const relations_commission_tiers = relations(commission_tiers, ({ many }) => ({
  benefits: many(commission_tiers_benefits, {
    relationName: 'benefits',
  }),
}))
export const relations_notifications_log = relations(notifications_log, ({ one }) => ({
  relatedAgent: one(agents, {
    fields: [notifications_log.relatedAgent],
    references: [agents.id],
    relationName: 'relatedAgent',
  }),
}))
export const relations_banners = relations(banners, ({ one }) => ({
  image: one(media, {
    fields: [banners.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_promos_items = relations(promos_items, ({ one }) => ({
  _parentID: one(promos, {
    fields: [promos_items._parentID],
    references: [promos.id],
    relationName: 'items',
  }),
}))
export const relations_promos = relations(promos, ({ many }) => ({
  items: many(promos_items, {
    relationName: 'items',
  }),
}))
export const relations_testimonials = relations(testimonials, ({ one }) => ({
  avatar: one(media, {
    fields: [testimonials.avatar],
    references: [media.id],
    relationName: 'avatar',
  }),
}))
export const relations_faqs = relations(faqs, () => ({}))
export const relations_blog_posts = relations(blog_posts, ({ one }) => ({
  featuredImage: one(media, {
    fields: [blog_posts.featuredImage],
    references: [media.id],
    relationName: 'featuredImage',
  }),
}))
export const relations__blog_posts_v = relations(_blog_posts_v, ({ one }) => ({
  parent: one(blog_posts, {
    fields: [_blog_posts_v.parent],
    references: [blog_posts.id],
    relationName: 'parent',
  }),
  version_featuredImage: one(media, {
    fields: [_blog_posts_v.version_featuredImage],
    references: [media.id],
    relationName: 'version_featuredImage',
  }),
}))
export const relations_providers = relations(providers, ({ one }) => ({
  logo: one(media, {
    fields: [providers.logo],
    references: [media.id],
    relationName: 'logo',
  }),
}))
export const relations_patch_providers = relations(patch_providers, ({ one }) => ({
  logo: one(media, {
    fields: [patch_providers.logo],
    references: [media.id],
    relationName: 'logo',
  }),
}))
export const relations_games = relations(games, ({ one }) => ({
  image: one(media, {
    fields: [games.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ one, many }) => ({
  avatar: one(media, {
    fields: [users.avatar],
    references: [media.id],
    relationName: 'avatar',
  }),
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    agentsID: one(agents, {
      fields: [payload_locked_documents_rels.agentsID],
      references: [agents.id],
      relationName: 'agents',
    }),
    'commission-tiersID': one(commission_tiers, {
      fields: [payload_locked_documents_rels['commission-tiersID']],
      references: [commission_tiers.id],
      relationName: 'commission-tiers',
    }),
    'notifications-logID': one(notifications_log, {
      fields: [payload_locked_documents_rels['notifications-logID']],
      references: [notifications_log.id],
      relationName: 'notifications-log',
    }),
    bannersID: one(banners, {
      fields: [payload_locked_documents_rels.bannersID],
      references: [banners.id],
      relationName: 'banners',
    }),
    promosID: one(promos, {
      fields: [payload_locked_documents_rels.promosID],
      references: [promos.id],
      relationName: 'promos',
    }),
    testimonialsID: one(testimonials, {
      fields: [payload_locked_documents_rels.testimonialsID],
      references: [testimonials.id],
      relationName: 'testimonials',
    }),
    faqsID: one(faqs, {
      fields: [payload_locked_documents_rels.faqsID],
      references: [faqs.id],
      relationName: 'faqs',
    }),
    'blog-postsID': one(blog_posts, {
      fields: [payload_locked_documents_rels['blog-postsID']],
      references: [blog_posts.id],
      relationName: 'blog-posts',
    }),
    providersID: one(providers, {
      fields: [payload_locked_documents_rels.providersID],
      references: [providers.id],
      relationName: 'providers',
    }),
    'patch-providersID': one(patch_providers, {
      fields: [payload_locked_documents_rels['patch-providersID']],
      references: [patch_providers.id],
      relationName: 'patch-providers',
    }),
    gamesID: one(games, {
      fields: [payload_locked_documents_rels.gamesID],
      references: [games.id],
      relationName: 'games',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))
export const relations_site_settings_social_links = relations(
  site_settings_social_links,
  ({ one }) => ({
    _parentID: one(site_settings, {
      fields: [site_settings_social_links._parentID],
      references: [site_settings.id],
      relationName: 'socialLinks',
    }),
  }),
)
export const relations_site_settings_ticker_messages = relations(
  site_settings_ticker_messages,
  ({ one }) => ({
    _parentID: one(site_settings, {
      fields: [site_settings_ticker_messages._parentID],
      references: [site_settings.id],
      relationName: 'tickerMessages',
    }),
  }),
)
export const relations_site_settings = relations(site_settings, ({ one, many }) => ({
  logo: one(media, {
    fields: [site_settings.logo],
    references: [media.id],
    relationName: 'logo',
  }),
  favicon: one(media, {
    fields: [site_settings.favicon],
    references: [media.id],
    relationName: 'favicon',
  }),
  heroImage: one(media, {
    fields: [site_settings.heroImage],
    references: [media.id],
    relationName: 'heroImage',
  }),
  socialLinks: many(site_settings_social_links, {
    relationName: 'socialLinks',
  }),
  ogImage: one(media, {
    fields: [site_settings.ogImage],
    references: [media.id],
    relationName: 'ogImage',
  }),
  tickerMessages: many(site_settings_ticker_messages, {
    relationName: 'tickerMessages',
  }),
}))
export const relations_popup_announcement = relations(popup_announcement, ({ one }) => ({
  image: one(media, {
    fields: [popup_announcement.image],
    references: [media.id],
    relationName: 'image',
  }),
}))

type DatabaseSchema = {
  enum_agents_experience: typeof enum_agents_experience
  enum_agents_status: typeof enum_agents_status
  enum_commission_tiers_icon: typeof enum_commission_tiers_icon
  enum_notifications_log_channel: typeof enum_notifications_log_channel
  enum_notifications_log_status: typeof enum_notifications_log_status
  enum_promos_icon: typeof enum_promos_icon
  enum_testimonials_type: typeof enum_testimonials_type
  enum_faqs_category: typeof enum_faqs_category
  enum_blog_posts_category: typeof enum_blog_posts_category
  enum_blog_posts_status: typeof enum_blog_posts_status
  enum__blog_posts_v_version_category: typeof enum__blog_posts_v_version_category
  enum__blog_posts_v_version_status: typeof enum__blog_posts_v_version_status
  enum_users_role: typeof enum_users_role
  enum_media_category: typeof enum_media_category
  enum_site_settings_social_links_platform: typeof enum_site_settings_social_links_platform
  enum_site_settings_scanner_seed_interval: typeof enum_site_settings_scanner_seed_interval
  agents_notes: typeof agents_notes
  agents: typeof agents
  commission_tiers_benefits: typeof commission_tiers_benefits
  commission_tiers: typeof commission_tiers
  notifications_log: typeof notifications_log
  banners: typeof banners
  promos_items: typeof promos_items
  promos: typeof promos
  testimonials: typeof testimonials
  faqs: typeof faqs
  blog_posts: typeof blog_posts
  _blog_posts_v: typeof _blog_posts_v
  providers: typeof providers
  patch_providers: typeof patch_providers
  games: typeof games
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  site_settings_social_links: typeof site_settings_social_links
  site_settings_ticker_messages: typeof site_settings_ticker_messages
  site_settings: typeof site_settings
  popup_announcement: typeof popup_announcement
  relations_agents_notes: typeof relations_agents_notes
  relations_agents: typeof relations_agents
  relations_commission_tiers_benefits: typeof relations_commission_tiers_benefits
  relations_commission_tiers: typeof relations_commission_tiers
  relations_notifications_log: typeof relations_notifications_log
  relations_banners: typeof relations_banners
  relations_promos_items: typeof relations_promos_items
  relations_promos: typeof relations_promos
  relations_testimonials: typeof relations_testimonials
  relations_faqs: typeof relations_faqs
  relations_blog_posts: typeof relations_blog_posts
  relations__blog_posts_v: typeof relations__blog_posts_v
  relations_providers: typeof relations_providers
  relations_patch_providers: typeof relations_patch_providers
  relations_games: typeof relations_games
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_site_settings_social_links: typeof relations_site_settings_social_links
  relations_site_settings_ticker_messages: typeof relations_site_settings_ticker_messages
  relations_site_settings: typeof relations_site_settings
  relations_popup_announcement: typeof relations_popup_announcement
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
